"""
faction_defs/imperial_guard.py — фракция «Имперская Гвардия»

Многочисленная пехота (max 12 Guardsmen!). Dominance позволяет развёртывать
2+ одинаковых юнита со скидкой. Warhound Titans поставляются с 3 жетонами подкрепления.
"""
from faction_base import Faction, UnitConfig, BattleCard, OrderUpgrade, CardLevel, EventCard

IMPERIAL_GUARD = Faction(
    id    = "imperial_guard",
    name  = "Imperial Guard",
    icon  = "⚜",
    color        = "#795548",
    home_tile_id = "home_imperial_guard",
    flavor = (
        "Dominate: When you resolve a dominate order, you may resolve a deploy order, "
        "only to purchase 2 or more identical units and placing them on either 1 friendly world "
        "containing a structure or 1 friendly or uncontrolled void. Reduce the materiel cost of each unit by 1."
    ),
    special_ability_name = "Dominate",
    special_ability_desc = (
        "When you resolve a dominate order, you may resolve a deploy order, "
        "only to purchase 2 or more identical units and placing them on either 1 friendly world "
        "containing a structure or 1 friendly or uncontrolled void. Reduce the materiel cost of each unit by 1."
    ),
    unit_config = UnitConfig(
        # ── Стартовый состав войск ──────────────────────────────────────────
        infantry=3, marines=2, mechanized=0, elite=0,
        fighters=1, destroyers=0,
        # ── Стартовые постройки ─────────────────────────────────────────────
        factories=1, cities=0, bastions=0,
        # ── Стартовые ресурсы ───────────────────────────────────────────────
        credits=6, support_tokens=0, discount_tokens=0, forge_tokens=0,
        # ── Характеристики юнитов ───────────────────────────────────────────
        unit_stats={
            "infantry":   dict(name="Guardsmen",                    cost=2,               combat_strength=1, health=1, morale=2, max_count=12),
            "marines":    dict(name="Ogryns",                       cost=3,               combat_strength=2, health=4, morale=2, max_count=6),
            "mechanized": dict(name="Leman Russ Battle Tanks",      cost=4,               combat_strength=3, health=4, morale=3, max_count=6),
            "elite":      dict(name="Warhound Titans",              cost=5, cost_forge=1, combat_strength=3, health=5, morale=4, max_count=3),
            "fighter":    dict(name="Lunar-Class Cruisers",         cost=2,               combat_strength=2, health=2, morale=2, max_count=3),
            "destroyer":  dict(name="Emperor-Class Battleships",    cost=5, cost_forge=1, combat_strength=4, health=6, morale=3, max_count=3),
        },
        # ── Стартовая колода боевых карт ──────────────────────────────────────
        battle_card_deck = [
            "Fire Support",
            "For the Emperor!",
            "Incoming!",
            "Iron Discipline",
            "Ratling Marksmen",
        ],
    ),
    battle_cards=[
        BattleCard(
            name="Fire Support",
            tier=-1,
            cost=0,
            icons={"G": 1, "S": 0, "M": 0},
            primary="If you are defending, gain 2 (s). Otherwise, opponent loses 2 (s).",
            secondary={"requires": ["Guardsman", "Cruiser"], "effect": "Reroll 1 [S]."},
            image="faction_defs/imperial_guard_data/battle/Fire Support.jpg",
        ),
        BattleCard(
            name="For the Emperor!",
            tier=-1,
            cost=0,
            icons={"G": 1, "S": 0, "M": 0},
            primary="Reroll 1 of your dice.",
            secondary={"requires": ["Guardsman", "Cruiser"],
                       "effect": "Gain 1 (g) for each unrouted Guardsman or Cruiser, to a maximum of 3."},
            image="faction_defs/imperial_guard_data/battle/For the Emperor!.jpg",
        ),
        BattleCard(
            name="Incoming!",
            tier=-1,
            cost=0,
            icons={"G": 0, "S": 1, "M": 0},
            primary="Gain 1 [?].",
            secondary={"requires": ["Guardsman", "Cruiser"],
                       "effect": "Gain 1 (s) for each unrouted Guardsman or Cruiser, to a maximum of 3."},
            image="faction_defs/imperial_guard_data/battle/Incoming!.jpg",
        ),
        BattleCard(
            name="Iron Discipline",
            tier=-1,
            cost=0,
            icons={"G": 0, "S": 0, "M": 1},
            primary="Gain 1 [?] for each of your unrouted units of a different Tier.",
            secondary={"requires": ["Guardsman", "Cruiser"], "effect": "Rally 1 of your units."},
            image="faction_defs/imperial_guard_data/battle/Iron Discipline.jpg",
        ),
        BattleCard(
            name="Ratling Marksmen",
            tier=-1,
            cost=0,
            icons={"G": 1, "S": 0, "M": 0},
            primary="At the start of the assess damage step of this execution round, your enemy loses 2 (g).",
            secondary={"requires": ["Guardsman", "Cruiser"],
                       "effect": "Your enemy chooses and routs 1 of his units unless he spends 1 die of his choice."},
            image="faction_defs/imperial_guard_data/battle/Ratling Marksmen.jpg",
        ),
        BattleCard(
            name="Bullgryn Bulwark",
            tier=0,
            cost=2,
            icons={"G": 0, "S": 2, "M": 0},
            primary="You must reroll 2 [G] or [M].",
            secondary={"requires": ["Ogryn", "Cruiser"],
                       "effect": "Gain 1 (g) for each unrouted Guardsman or Cruiser, to a maximum of 3."},
            image="faction_defs/imperial_guard_data/battle/Bullgryn Bulwark.jpg",
        ),
        BattleCard(
            name="Mechanised Combat Group",
            tier=0,
            cost=2,
            icons={"G": 1, "S": 1, "M": 1},
            primary="At the start of the assess damage step of this execution round, your enemy loses either 3 (g) or 3 (s) for each pairing of unrouted Guardsmen with Ogryns or Cruisers with Battleships.",
            secondary={"requires": ["-"], "effect": "-"},
            image="faction_defs/imperial_guard_data/battle/Mechanised Combat Group.jpg",
        ),
        BattleCard(
            name="Ogryn Shock Troops",
            tier=0,
            cost=2,
            icons={"G": 2, "S": 0, "M": 0},
            primary="You must reroll 2 [S] or [M].",
            secondary={"requires": ["Ogryn", "Cruiser"],
                       "effect": "Gain 1 (s) for each unrouted Guardsman or Cruiser, to a maximum of 3."},
            image="faction_defs/imperial_guard_data/battle/Ogryn Shock Troops.jpg",
        ),
        BattleCard(
            name="Sentinel Reconnaissance",
            tier=0,
            cost=2,
            icons={"G": 0, "S": 1, "M": 0},
            primary="If you have more unrouted units than your enemy, your enemy chooses and routs 1 of his units unless he spends 1 [M].",
            secondary={"requires": ["Ogryn", "Cruiser"],
                       "effect": "If you are attacking, look at your enemy's facedown combat. Gain either 2 [G] or 2 [S]."},
            image="faction_defs/imperial_guard_data/battle/Sentinel Reconnaissance.jpg",
        ),
        BattleCard(
            name="Armoured Spearhead",
            tier=2,
            cost=4,
            icons={"G": 3, "S": 0, "M": 0},
            primary="Either destroy up to 2 unrouted Guardsmen to force your enemy to lose 2 dice of his choice for each destroyed Guardsman or destroy 1 unrouted Cruiser to force your enemy to lose 3 dice of his choice.",
            secondary={"requires": ["Leman Russ", "Battleship"],
                       "effect": "Choose 1 of your enemy's Tier 2 or Tier 3 units or bastions. That unit or bastion suffers damage first during this execution round."},
            image="faction_defs/imperial_guard_data/battle/Armoured Spearhead.jpg",
        ),
        BattleCard(
            name="Combined Arms",
            tier=2,
            cost=4,
            icons={"G": 1, "S": 1, "M": 0},
            primary="For each of your unrouted ground units of a different Tier, gain either 1 (g) or 1 (s). For each of your unrouted ships of a different Tier, gain either 2 (g) or 2 (s). Gain 1 [?]. Rally 1 of your units.",
            secondary={"requires": ["-"], "effect": "-"},
            image="faction_defs/imperial_guard_data/battle/Combined Arms.jpg",
        ),
        BattleCard(
            name="Wyvern Suppresion Fire",
            tier=2,
            cost=4,
            icons={"G": 1, "S": 2, "M": 0},
            primary="If you have more unrouted Tier 0 units than your enemy, your enemy chooses and routs 1 of his units.",
            secondary={"requires": ["Leman Russ", "Battleship"],
                       "effect": "Your enemy chooses and destroys 1 of his routed Tier 0 or Tier 1 units."},
            image="faction_defs/imperial_guard_data/battle/Wyvern Suppresion Fire.jpg",
        ),
        BattleCard(
            name="Hammer of the Emperor",
            tier=3,
            cost=6,
            icons={"G": 3, "S": 0, "M": 1},
            primary="Force your enemy to lose 1 [S].",
            secondary={"requires": ["Warhound Titan", "Battleship"],
                       "effect": "Warhound Titan: Gain 2 (g) for each of your unrouted units of a different Tier, to a maximum of 6. Battleship: Gain 3 (g) for each of your unrouted units of a different Tier."},
            image="faction_defs/imperial_guard_data/battle/Hammer of the Emperor.jpg",
        ),
        BattleCard(
            name="Titan Support",
            tier=3,
            cost=6,
            icons={"G": 1, "S": 2, "M": 2},
            primary="Your enemy must reroll 1 [G] for each of your unrouted units of a different Tier.",
            secondary={"requires": ["Warhound Titan", "Battleship"],
                       "effect": "During this execution round, your units of Tier 2 or less cannot become routed."},
            image="faction_defs/imperial_guard_data/battle/Titan Support.jpg",
        ),
    ],
    order_upgrades=[
        OrderUpgrade(
            name="Saturation Bombing",
            order_type="advance",
            tier=0,
            cost=1,
            primary="Orbital Strike, once per round. Gain 1 [?].",
            secondary="You may convert 1 of your [M] into 1 [G].",
            image="faction_defs/imperial_guard_data/order/Saturation Bombing.jpg",
        ),
        OrderUpgrade(
            name="Adeptus Astronomica",
            order_type="advance",
            tier=1,
            cost=2,
            primary="While resolving this order, you may move up to 6 units to a world, if at least 1 of those units is a Guardsman. Once per round.",
            secondary="After you resolve this order, you may retreat any Guardsmen in excess of that world's unit capacity. Command Level 1.",
            image="faction_defs/imperial_guard_data/order/Adeptus Astronomica.jpg",
        ),
        OrderUpgrade(
            name="Departmento Munitorum",
            order_type="strategize",
            tier=1,
            cost=2,
            primary="While resolving this order, you may purchase 1 upgrade only. Then resolve a limited Deploy, Advance, or Dominate order in the active system. Once per round.",
            secondary="Command Level 1.",
            image="faction_defs/imperial_guard_data/order/Departmento Munitorum.jpg",
        ),
        OrderUpgrade(
            name="Forced Recruitment",
            order_type="deploy",
            tier=1,
            cost=2,
            primary="While resolving this order, you may treat all your cities in the active system as factories capable of deploying Guardsmen only. The unit capacity of friendly worlds containing a city is increased by 2, to a maximum of 4 (Guardsmen only). Once per round.",
            secondary="Command Level 1.",
            image="faction_defs/imperial_guard_data/order/Forced Recruitment.jpg",
        ),
        OrderUpgrade(
            name="Virus Bombs",
            order_type="advance",
            tier=2,
            cost=3,
            primary="Orbital Strike, once per round. Enemy bastions do not prevent orbital strike.",
            secondary="During this orbital strike, the health value of your enemy's units is reduced to 3. Command Level 2.",
            image="faction_defs/imperial_guard_data/order/Virus Bombs.jpg",
        ),
    ],

    event_cards=[
        EventCard(name="Call of the Astropaths", warp_storm_move="Across", card_type="Scheme",
                  effect="At the end of a reinforce step of combat, if you are defending, you may discard this card to place 2 free (R) in the contested area.",
                  image="faction_defs/imperial_guard_data/events/Call of the Astropaths.jpg"),
        EventCard(name="Deathstrike Missile", warp_storm_move="Sideways", card_type="Scheme",
                  effect="You may discard this card at the start of combat on any world. If you do, either destroy 1 Tier 0 or 1 Tier 1 unit on that world or rout 1 Tier 2 unit on that world at the end of the first assess damage step.",
                  image="faction_defs/imperial_guard_data/events/Deathstrike Missile.jpg"),
        EventCard(name="Order of the High Command", warp_storm_move="Top Left/Bot Rgt", card_type="Tactic",
                  effect="Purchase 1 combat upgrade, reducing its materiel cost by 1 for each friendly world containing a factory.",
                  image="faction_defs/imperial_guard_data/events/Order of the High Command.jpg"),
        EventCard(name="Imperial Tithe", warp_storm_move="Top Rgt/Bot Left", card_type="Tactic",
                  effect="Either place 2 free Guardsmen on 1 friendly world in a system containing at least 1 of your factories or place 1 free Guardsman on any friendly world.",
                  image="faction_defs/imperial_guard_data/events/Imperial Tithe.jpg"),
        EventCard(name="Military Production Shift", warp_storm_move="Across", card_type="Tactic",
                  effect="Choose a friendly world. Gain assets from this world and gain materiel equal to its materiel value.",
                  image="faction_defs/imperial_guard_data/events/Military Production Shift.jpg"),
        EventCard(name="Lance Strike", warp_storm_move="Top Rgt/Bot Left", card_type="Scheme",
                  effect="Before you perform an orbital strike, you may discard this card to add 2 to the total amount of damage suffered by your enemy's units.",
                  image="faction_defs/imperial_guard_data/events/Lance Strike.jpg"),
        EventCard(name="Tactical Genius", warp_storm_move="Top Left/Bot Rgt", card_type="Scheme",
                  effect="Instead of playing a combat card from your hand, you may discard this card to play any card from either your combat deck or your upgrade deck, other than a card that has already been played.",
                  image="faction_defs/imperial_guard_data/events/Tactical Genius.jpg"),
        EventCard(name="Tempestus Scions", warp_storm_move="Sideways", card_type="Tactic",
                  effect="Rout 1 enemy Tier 0 or Tier 1 unit that is either in a system containing at least 1 of your units or in an adjacent system.",
                  image="faction_defs/imperial_guard_data/events/Tempestus Scions.jpg"),
    ],

    extra = {
        "homeworld":    "Cadia",
        "color_scheme": "#795548",
    },
)
